Project/Models/ApplicationUserClass.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Project.Data.Models;
using Project.Models;


namespace Project.Models
{
    public class ApplicationUserClass:IdentityDbContext

    {
        public ApplicationUserClass(DbContextOptions<ApplicationUserClass> options):base(options)

        {

        }
        public DbSet<UserRegClass> UserTable { get; set; }
        public DbSet<Project.Models.LoginViewClass> LoginViewClass { get; set; }

        public DbSet<ImageClass> ImageClass { get; set; }
        public DbSet<Tag> Tag { get; set; }


    }
}

Project/Models/ErrorViewModel.cs
using System;

namespace Project.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Project/Models/ImageClass.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Project.Models
{
    public class ImageClass
    {


        [Key]
        public int Photo_Id { get; set; }
        public string Name { get; set; }
        public DateTime CaptureDate { get; set; }
        public string Geolocation { get; set; }
        public string CaptureBy { get; set; }
        public virtual IEnumerable <Tag> Tag { get; set; }
       

    }
}

Project/Models/ImageModel.cs
using Project.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Project.Models
{
    public class ImageModel
    {
        public IEnumerable<ImageClass> image { get; set; }
        public string Search { get; set; }
    }
}

Project/Models/LoginViewClass.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Project.Models
{
    public class LoginViewClass
    {
        [Key]
        public int Id { get; set; }


        [Required(ErrorMessage = "Please Enter your User Name ")]
        [Display(Name = "User Name")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Please Enter the password ")]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }
    }
}

Project/Models/Tag.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Project.Models
{
    public class Tag
    {
        public int TagId { get; set; }
        public string Description { get; set; }
    }
}

Project/Models/UserRegClass.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Project.Models
{
    public class UserRegClass
    {
        [Key]
        public int Id{ get; set; }

        [Required]//(ErrorMessage ="Please Enter your First Name")]
        [Display(Name = "First Name")]
        public string User_Fname { get; set; }

        [Required]//(ErrorMessage = "Please Enter your Surname")]
        [Display(Name = "Surname")]
        public string User_Lname { get; set; }

        [Required]//(ErrorMessage = "Please Enter your Email Address")]
        [Display(Name = "Email Address")]
        public string User_Email { get; set; }

        [Required]//(ErrorMessage = "Please Enter your preffered User Name (ususally your First Name)")]
        [Display(Name = "User Name")]
        public string UserName { get; set; }

        [Required]//(ErrorMessage = "Please Enter the password you want to use")]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }


        [Required]//(ErrorMessage = "Please Enter Password again")]
        [DataType(DataType.Password)]
        [Compare("Password",ErrorMessage = "Password does not match")]
        [Display(Name = "Confirm Password")]
        public string ConPass { get; set; }


    }
}

Project/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Project.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Project/Controllers/ImageController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using Project.Data;
using Project.Data.Models;
using Project.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;


namespace Project.Controllers
{
    public class ImageController : Controller
    {
        private readonly Images _service;
        public ImageController(Images service)
        {
            _service = service;
        }
        public IActionResult Image()
        {
            var photolist = _service.GetAll();
            var model = new ImageModel()
            {
                image = photolist,
                Search = ""
            };

            return View(model);


        }
        public IActionResult Detail(int photoId)
        {
            var image = _service.GetId(photoId);

            var model = new ImageClass()
            {
                Photo_Id = image.Photo_Id,
                Name = image.Name,
                CaptureDate = image.CaptureDate,
                Geolocation = image.Geolocation,
                CaptureBy = image.CaptureBy,
                Tag = (IEnumerable<Tag>)image.Tag.Select(tg => tg.Description).ToList()


            };
            return View(model);
                
        }
    }


 



}

Project/Controllers/UserRegistrationController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Project.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Configuration;



namespace Project.Controllers
{
    public class UserRegistrationController : Controller
    {
        private readonly UserManager<IdentityUser> userMan;
        private readonly SignInManager<IdentityUser> signIn;

        public UserRegistrationController(UserManager<IdentityUser> userMan, SignInManager<IdentityUser> signIn)
        {
            this.userMan = userMan;
            this.signIn = signIn;
        }
        [HttpPost]
        public async Task<IActionResult> Logout()
        {
           await signIn.SignOutAsync();
            return RedirectToAction("index", "home");

        }
     
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View();

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(UserRegClass userReg)
        {
          if(ModelState.IsValid)
            {
                var user = new IdentityUser { UserName = userReg.UserName };
                var x = await userMan.CreateAsync(user, userReg.Password);

                if(x.Succeeded)
                {
                    await signIn.SignInAsync(user, isPersistent: false);
                    return RedirectToAction("image", "gallery");
                }
                foreach(var error in x.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(userReg);
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();

        }
        [HttpPost]
       
        public async Task<IActionResult> Login(LoginViewClass log)
        {
            if (ModelState.IsValid)
            {

                var x = await signIn.PasswordSignInAsync(log.UserName, log.Password, false, false);

                if (x.Succeeded)
                {
               
                    return RedirectToAction("index", "home");
                }
             
                
                    ModelState.AddModelError(string.Empty, "Log in failed");
                
            }
            return View(log);
        }
       





        }

}

Project/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
   
</div>

Project/Views/Image/Image.cshtml
@model IEnumerable<Project.Data.Models.ImageClass>

@{
    ViewData["Title"] = "Image";
}

<h1>Image</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CaptureDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Geolocation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CaptureBy)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CaptureDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Geolocation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CaptureBy)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Photo_Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Photo_Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Photo_Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Project/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser>  signIn;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Project</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @if (signIn.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <form method="post" asp-action="logout" asp-controller="UserRegistration">
                                    <button type="submit" class="nav-link btn btn-link py-0" style="width:auto">
                                        Logout @User.Identity.Name
                                    </button>
                                </form>

                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserRegistration" asp-action="Create">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserRegistration" asp-action="Login">Login</a>
                            </li>
                        }



                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Image" asp-action="Image">Image</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Image" asp-action="Upload">Upload</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Project/Views/UserRegistration/Create.cshtml
@model UserRegClass

@{
    ViewData["Title"] = "Create";
}

<h1>User Registration</h1>


<hr />
<div class="row">
    <div class="col-md-10">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
         
            <div class="form-group">
                <label asp-for="User_Fname" class="control-label"></label>
                <input asp-for="User_Fname" class="form-control" />
                <span asp-validation-for="User_Fname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="User_Lname" class="control-label"></label>
                <input asp-for="User_Lname" class="form-control" />
                <span asp-validation-for="User_Lname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="User_Email" class="control-label"></label>
                <input asp-for="User_Email" class="form-control" />
                <span asp-validation-for="User_Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control"  />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" type ="password" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConPass" class="control-label"></label>
                <input asp-for="ConPass" class="form-control" type ="password" />
                <span asp-validation-for="ConPass" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            <b>@ViewBag.message</b>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Project/Views/UserRegistration/Login.cshtml
@model Project.Models.LoginViewClass

@{
    ViewBag.Title = "User login";
}

<h1>User Login</h1>

<h4>LoginViewClass</h4>
<hr />
<div class="row">
    <div class="col-md-10">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
           
                <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>